sudo: enabled
dist: trusty
language: node_js
node_js:
- "9"
script:
- npm install
- npm run webpack
- npm run tslint
- npm run test
- eval "$(ssh-agent -s)"
- ssh-keyscan -H 207.154.217.185 >> ~/.ssh/known_hosts
- chmod 600 $HOME/.ssh/deploy
- ssh-add $HOME/.ssh/deploy
- scp -r /home/travis/build/MaxSamokhin/playground/public/built root@207.154.217.185:/var/www/playground
before_install:
- openssl aes-256-cbc -K $encrypted_6bcd37e4cff3_key -iv $encrypted_6bcd37e4cff3_iv
  -in deploy.enc -out $HOME/.ssh/deploy -d
