export const USER_REQUEST = 'USER_REQUEST';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const USER_ERROR_SERVER = 'USER_ERROR_SERVER';
export const USER_LOG_OUT = 'USER_LOG_OUT';
